const dogs = [
    { id: 'dog-1',
      species: 'dog',
      img: require("../../assets/images/dog-1.jpeg")},
    { id: 'dog-2',
      species: 'dog',
      img: require("../../assets/images/dog-2.jpeg")},
    { id: 'dog-3',
      species: 'dog',
      img: require("../../assets/images/dog-3.jpeg")},
    { id: 'dog-4',
      species: 'dog',
      img: require("../../assets/images/dog-4.jpeg")},
    { id: 'dog-5',
      species: 'dog',
      img: require("../../assets/images/dog-5.jpeg")},
    { id: 'dog-6',
      species: 'dog',
      img: require("../../assets/images/dog-6.jpeg")},
    { id: 'dog-7',
      species: 'dog',
      img: require("../../assets/images/dog-7.jpeg")},
    { id: 'dog-8',
      species: 'dog',
      img: require("../../assets/images/dog-8.jpeg")},
    { id: 'dog-9',
      species: 'dog',
      img: require("../../assets/images/dog-9.jpeg")},
    { id: 'dog-10',
      species: 'dog',
      img: require("../../assets/images/dog-10.jpeg")}
  ]


const cats = [
    { id: 'cat-1',
      species: 'cat',
      img: require("../../assets/images/cat-1.jpeg") },
    { id: 'cat-2',
      species: 'cat',
      img: require("../../assets/images/cat-2.jpeg") },
    { id: 'cat-3',
      species: 'cat',
      img: require("../../assets/images/cat-3.jpeg") },
    { id: 'cat-4',
      species: 'cat',
      img: require("../../assets/images/cat-4.jpeg") },
    { id: 'cat-5',
      species: 'cat',
      img: require("../../assets/images/cat-5.jpeg") },
    { id: 'cat-6',
      species: 'cat',
      img: require("../../assets/images/cat-6.jpeg") },
    { id: 'cat-7',
      species: 'cat',
      img: require("../../assets/images/cat-7.jpeg") },
    { id: 'cat-8',
      species: 'cat',
      img: require("../../assets/images/cat-8.jpeg") },
    { id: 'cat-9',
      species: 'cat',
      img: require("../../assets/images/cat-9.jpeg") },
    { id: 'cat-10',
      species: 'cat',
      img: require("../../assets/images/cat-10.jpeg") }
  ]

const monkies = [
    { id: 'monkey-1',
      species: 'monkey',
      img: require("../../assets/images/monkey-1.jpeg") },
    { id: 'monkey-2',
      species: 'monkey',
      img: require("../../assets/images/monkey-2.jpeg") },
    { id: 'monkey-3',
      species: 'monkey',
      img: require("../../assets/images/monkey-3.jpeg") },
    { id: 'monkey-4',
      species: 'monkey',
      img: require("../../assets/images/monkey-4.jpeg") }
  ]

const horses = [
    { id: 'horse-1',
      species: 'horse',
      img: require("../../assets/images/horse-1.jpeg") },
    { id: 'horse-2',
      species: 'horse',
      img: require("../../assets/images/horse-2.jpeg") },
    { id: 'horse-3',
      species: 'horse',
      img: require("../../assets/images/horse-3.jpeg") },
    { id: 'horse-4',
      species: 'horse',
      img: require("../../assets/images/horse-4.jpeg") }
  ]

const cows = [
    { id: 'cow-1',
      species: 'cow',
      img: require("../../assets/images/cow-1.jpeg") },
    { id: 'cow-2',
      species: 'cow',
      img: require("../../assets/images/cow-2.jpeg") },
    { id: 'cow-3',
      species: 'cow',
      img: require("../../assets/images/cow-3.jpeg") },
    { id: 'cow-4',
      species: 'cow',
      img: require("../../assets/images/cow-4.jpeg") },
    { id: 'cow-5',
      species: 'cow',
      img: require("../../assets/images/cow-5.jpeg") }
  ]

export const animals = [...cats, ...dogs, ...monkies, ...horses, ...cows]